env:
<<<<<<< HEAD
  es6: true
  node: true
extends: eslint:recommended
=======
  commonjs: true
  es6: true
  node: true
extends:
  - standard
>>>>>>> cbdbc6039136b7b39ebc9fcaaf43cdecb1598001
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
<<<<<<< HEAD
  ecmaVersion: 2020
rules:
  arrow-parens:
    - error
    - always
  arrow-spacing: error
  block-spacing: error
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  comma-spacing:
    - error
    - after: true
      before: false
  eol-last:
    - error
    - always
  indent:
    - error
    - tab
    - SwitchCase: 1
  linebreak-style:
    - error
    - windows
  no-case-declarations: off
  no-empty: off
  no-irregular-whitespace: off
  no-prototype-builtins: off
  no-trailing-spaces: error
  no-unused-vars: off
  no-useless-escape: off
  object-curly-newline:
    - error
    - multiline: true
  object-curly-spacing:
    - error
    - always
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - double
  semi:
    - error
    - always
  space-before-function-paren:
    - error
    - never
  space-in-parens: error
=======
  ecmaVersion: 2019
rules:
  linebreak-style:
    - error
    - windows
  object-shorthand:
    - error
    - always
  no-case-declarations: off
  no-new: off
  no-prototype-builtins: off
  no-useless-constructor: off
  prefer-promise-reject-errors: off
>>>>>>> cbdbc6039136b7b39ebc9fcaaf43cdecb1598001
