env:
  commonjs: true
  es6: true
  node: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  process: readonly
  member: readonly
  server: readonly
  cache: readonly
  alert: readonly
  Audio: readonly
parserOptions:
  ecmaVersion: 2019
rules:
  linebreak-style:
    - error
    - windows
  object-shorthand:
    - error
    - always
  no-case-declarations: off
  no-new: off
  no-prototype-builtins: off
  no-useless-constructor: off
  prefer-promise-reject-errors: off
