name: Lint

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - master
    paths:
      - "actions"
      - "events"
      - "extensions"

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: 12

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run ESLint
        run: yarn lint
