name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "This issue is being marked as stale since it hasn't had any recent activity."
        stale-pr-message: "This pull request is being marked as stale since it hasn't had any recent activity."
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
